import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const outfitFont = Outfit({
  subsets: ["latin"],
});


export const metadata = {
  title: "Pixgen AI Art",
  description: "Generated by AI Image",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfitFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
